# fab sync_master_code:/var/www/opencsp

SYNC_CONF = [
		#("applications/markertracker", "applications"),
		#("applications/fliescourtship", "applications"),
		#("applications/backgroundcalculator", "applications"),
		#("applications/simplemousetracker", "applications"),
		#("applications/fliescourt", "applications"),
		#("applications/singlefly", "applications"),
		#("applications/simplemousetracker", "applications"),
		#("applications/blobtracker", "applications"),
		#("applications/motioncounter", "applications"),
		#("applications/dolphintracker", "applications"),
		#("/home/ricardo/subversion/MEShTracker/Calibrator/Simulator", "applications/dolphintracker"),
		#("applications/calibratecam", "applications"),
		#("applications/mergevideos", "applications"),
		#("applications/convertvideo", "applications"),
		#("applications/backupvideo", "applications"),
		#("applications/replaceblobsperballs", "applications"),
		#("applications/imageregistration", "applications"),
		#("applications/imageregistration2", "applications"),
		#("applications/imageregistrationcmtk322", "applications"),
		#("applications/imageregistrationants", "applications"),
		#("applications/spikesorter", "applications"),
		#("/home/ricardo/subversion/opencsp/applications/copytest", "applications"),
		#("/home/ricardo/subversion/OpenCSP-SingleFly/", "applications/singlefly"),
		#("/home/ricardo/subversion/OpenCSP-Elastix/", "applications/elastix"),
		("/home/ricardo/subversion/OpenCSP-Ilastik/", "applications/ilastik"),
		("/home/ricardo/subversion/OpenCSP-Transformix/", "applications/transformix"),
		#("/home/ricardo/subversion/OpenCSP-FliesCourtNoArena/", "applications/fliescourtnoarena"),
		("/home/ricardo/subversion/OpenCSP-PrepareFilesForBrainRegistration/src/", "applications/preparefilesforbrainregistration"),
		("/home/ricardo/subversion/OpenCSP-Elastix/src/", "applications/elastix"),
		
		
		#("server/slave", ""),
		#("/home/ricardo/subversion/pyforms/pyforms", "slave/framework"),
		#("/home/ricardo/subversion/opencsp/server/opencsp/envmanagers/DefaultEnvManager/DefaultEnvManager.py", "opencsp/envmanagers/"),

		#("server/Simulator", ""),
		#("server/media", ""),
		#("server/wwc", ""),
		#("server/scripts", ""),
		#("server/fabfile.py", ""),
		#("server/Utils", ""),
		#("server/slave/kill.sh", "slave"),
		#("server/slave/stop.sh", "slave"),
		#("server/slave/framework", "slave"),
		#("server/server", ""),
		#("server/filesbrowser", ""),
		#("server/processing_app/models.py", "processing_app/models.py"),
		#("server/opencsp", ""),
		#("server/webservices", ""),
		#("/home/ricardo/subversion/opencsp/server/opencsp/server/opencsp/modelsfiles/Server.py", "opencsp"),
		#("server/opencsp/plugins", "opencsp"),
		#("server/opencsp/envmanagers", "opencsp"),
		#("server/opencsp/storagemanagers", "opencsp"),
		#("server/static", ""),
		#("../server/templates", ""),
		#("server/static/css", "static"),
		#("server/static/img", "static"),
		#("server/static/js/jobs.js", "static/js/jobs.js"),
		#("../server/static/js/framework.js", "static/js/framework.js"),
		#("server/templates_openid", ""),
		#("server/wwc/RemoteExecuter.py", "wwc/AutoForm.py/RemoteExecuter.py"),
		#("server/check_for_new.py", "check_for_new.py"),
		#("server/finnish_process.py", "finnish_process.py"),
		#("server/manage.py", "manage.py"),
		#("server/processing_app/ApplicationsSettings.py", "processing_app/ApplicationsSettings.py"),
	]
